### ISSUE TITLE
to: wrong arguments

### ISSUE THREAD

**Issue by mattqs** [jprichardson/string.js#127]
I do:
   
    var S = require('string');

and I get on the console output:

    to: wrong argument

What am I doing wrong?

**Comment by jprichardson** [comment]
How did you install string.js? That console output is coming from `shelljs` which is only included if you install with `npm install --development`.

**Comment by mattqs** [comment]
I did 'npm install string --save'. I'm running a grunt mocha test with config:

      mode5: {
          src    : ['<%= spa_path %>/tests/modes/mode5/*.js'],
          options: {
            timeout: 20000,
            reporter: 'xunit',
            captureFile: '<%= test_report_dir %>/mocha_mode5.xml'
          }

If I use the string module wihtin my test I'm getting the `to: wrong argument` output into my xml file, which makes that xml invalid.

**Comment by az7arul** [comment]
@jprichardson you might want to look at [this](https://github.com/paazmaya/grunt-trimtrailingspaces/issues/1) too

**Comment by jprichardson** [comment]
Ya, I think I'll just drop shell.js, as it's pretty annoying that it modifies the string prototype. See here: https://github.com/arturadib/shelljs/issues/159

**Comment by jprichardson** [comment]
Actually, shell.js isn't even being included as a dev dependency....

**Comment by jprichardson** [comment]
*sigh*... I'll have to figure out a workaround. I'm not sure what'd that be... maybe string.js checks for the `.to` method on the native string prototype and skip it if it's found? @az7arul thoughts?

**Comment by az7arul** [comment]
@jprichardson  I didn't find anything like that ( without thoroughly checking ) but I am looking into this.

**Comment by az7arul** [comment]
so the `getNativeStringProperties` method calls String.to without an argument

**Comment by myndzi** [comment]
I just ran down an annoying bug and it comes back to string.js's behavior of instantiating every native method of String, which interacts with shelljs to create a file called 'string' with the contents 'testtest' in the current working directory.

I'm not sure string.js should be doing this iteration, and I'm not sure why it's there; what is the purpose of this loop in getNativeStringProperties? It looks like you're trying to inherit the native prototype, but Object.create might be a better choice here -- and why call the functions to begin with?

**Comment by az7arul** [comment]
I am assuming it was there to find out which String prototype methods return string to wrap them in stringjs methods. But it seems it causing more problems than it actually solves.

**Comment by myndzi** [comment]
That does make some sense; it may be that the only decent way to do this would be to wrap them in a function instead.

**Comment by jprichardson** [comment]
> I am assuming it was there to find out which String prototype methods return string to wrap them in stringjs methods. 

This is correct. However, I'm not aware of any problems that it's caused other than modules that modify the string prototype AND explicitly write to the console if arguments aren't provide - which is `shelljs`. I'm open to changing the behavior though if alternatives are presented.

**Comment by az7arul** [comment]
yeah, I meant causing problems for shelljs, we added a 2nd argument to fix `to: wrong argument` in console.log  but now the fix creates a file!

**Comment by jprichardson** [comment]
Wow. Why not just look for a function named `to` and skip it? If platform doesn't support `Function.prototype.name`, we could use this in its place: http://stackoverflow.com/a/17923727/10333

**Comment by jprichardson** [comment]
Or we could just ignore it altogether until shelljs decides to ever fix its non-idiomatic behavior.

**Comment by myndzi** [comment]
Or we could not call a bunch of functions when we don't know what they do...

**Comment by myndzi** [comment]
> I'm open to changing the behavior though if alternatives are presented.

- Create and ship an explicit list of the functions that you want to provide based on the currently supported version(s) of Node; this can be a pre-publish hook and autogenerated, even

or

- Write a wrapper function that calls a function with arguments and instantiates the result as an "S" if it's a string; use this function to wrap all the prototype methods and add the wrapped versions to S.prototype. If you want to get fancy, memoize the return value and remove the wrapper at first opportunity.
