### ISSUE TITLE
method to capitalize all words, not just one

### ISSUE THREAD

**Issue by chovy** [jprichardson/string.js#132]
Would it be possible to add a method `S('senior javascript engineer').capitalizeAll()` that would return `Senior Javascript Engineer` for example?

The current `.capitalize()` only does the first word.

**Comment by az7arul** [comment]
@chovy I think `titlelize` is the method name used for this which string.js does not have right now. You can create a pr for it if you want to.

**Comment by tanvirraj** [comment]
@az7arul  i think this issue should be close 
there is a pull request https://github.com/jprichardson/string.js/pull/88 for this

**Comment by danieldiekmeier** [comment]
This was added in 3.2.0, see #149
