### ISSUE TITLE
Webpack complaining about string.js being already pre-built

### ISSUE THREAD

**Issue by stevewillard** [jprichardson/string.js#142]
I have been using string.js 3.1.1 with Webpack successfully. When I upgraded to 3.1.2, I'm now getting the warning:
```
WARNING in ./~/string/dist/string.js
Critical dependencies:
1:401-408 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/string/dist/string.js 1:401-408
```

Things seem to still work, just thought I'd let you know that there's a warning now.

**Comment by az7arul** [comment]
Thanks, I think I know what happened. In 3.1.2 package.json's `main` attribute points to `dist/string` which is already browserified instead of previous `lib/string`.

**Comment by jprichardson** [comment]
Yeah, unless I'm missing a benefit of `dist`, `main` should be `lib/string`.

**Comment by az7arul** [comment]
releasing 3.1.3 with this fix

**Comment by stevewillard** [comment]
Works great -- thanks
