### ISSUE TITLE
Add rsplit

### ISSUE THREAD

**Issue by danieldiekmeier** [jprichardson/string.js#150]
For a project I just needed something like Python's [rsplit](https://docs.python.org/2/library/stdtypes.html#str.rsplit), but I was sad to see that it isn't available in string.js.

Would it be possible to add it?

Example code from [this StackOverflow question](http://stackoverflow.com/questions/5202085/javascript-equivalent-of-pythons-rsplit):

```javascript
String.prototype.rsplit = function(sep, maxsplit) {
    var split = this.split(sep);
    return maxsplit ? [ split.slice(0, -maxsplit).join(sep) ].concat(split.slice(-maxsplit)) : split;
}
```

**Comment by az7arul** [comment]
Its a nice to have, can you create a PR for this ? 

[These](https://github.com/python/cpython/blob/829b49cbd2e4b1d573470da79ca844b730120f3d/Lib/test/string_tests.py#L424) specs can be helpful to ensure they work as python

**Comment by jprichardson** [comment]
For naming continuity with other methods, let's name it `splitRight`.

**Comment by danieldiekmeier** [comment]
I started implementing this, but just noticed something:

The JavaScript [`String.prototype.split()` implementation](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/split) differs from the way [`String.split()`](https://docs.python.org/2/library/stdtypes.html#str.split) in Python works.

Javascript:
```javascript
'a|b|c|d'.split('|', 2)
// [ 'a', 'b' ]
```

Python:
```python
"a|b|c|d".split("|", 2)
# ['a', 'b', 'c|d']
```

The limit in JavaScript describes the length of the returned array, but in Python it's actually the number of splits that are made.

I'd rather have the Python way (for split AND rightSplit), but the JavaScript way would of course be more consistent. Do you have an idea what to do?

**Comment by az7arul** [comment]
IMO, we should not change behaviour of `split` for javascript, but for `rsplit` we can have it like 

```js
function([sep[, limit, maxSplit]] { ...
```

what do you think ?

**Comment by danieldiekmeier** [comment]
But is `sep, limit, maxSplit` the right order? How will we do something like `sep, maxSplit`? 

Maybe with `sep, 0, maxSplit`? (Or `-1`, `false`, or `null`?)

We could probably add a `splitLeft` that takes the same parameters as `splitRight`, to mirror the behaviour?

**Comment by az7arul** [comment]
you are right, `sep, limit, maxSplit` does not seem to be right, may be go for `sep, maxSplit, limit` since maxSplit seems to be the main parameter and limit will default to full string length.

+1 for splitLeft, it will give the python's version of split ( and a js version that accepts maxSplit parameter)

**Comment by danieldiekmeier** [comment]
Okay, I'll get on it as soon as I find the time. Thank you for your feedback, I appreciate it!
