### ISSUE TITLE
Trim not removing zero-width spaces

### ISSUE THREAD

**Issue by paleite** [jprichardson/string.js#182]
It seems trim() no longer removes zero-width spaces.
Specifically 200B: https://codepoints.net/U+200B

**Comment by romellem** [comment]
If you wanted to implement this yourself, you might try something like this:

```
trim: function() {
      var s;
      if (typeof __nsp.trim === 'undefined')
        s = this.s.replace(/(^[\s\u200b]*|[\s\u200b]*$)/g, '')
      else
        s = this.s.trim()
      return new this.constructor(s);
    }
```

However, that wouldn't work (at least in NodeJS) and after looking into this a bunch, I think I discovered why `.trim()` doesn't (and shouldn't) remove `\u200B` on the outside of strings.

___

In the [ECMAScript 2015](http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.trim) definition for `String.prototype.trim()`, they define what leading and trailing *WhiteSpace* gets removed:

> The definition of white space is the union of [*WhiteSpace*](http://www.ecma-international.org/ecma-262/6.0/#table-32) and [*LineTerminator*](http://www.ecma-international.org/ecma-262/6.0/#table-33).

So looking at how they define [*WhiteSpace*](http://www.ecma-international.org/ecma-262/6.0/#table-32), it doesn't explicitly name `U+200B` as a white space character. It does name *Other category "Zs"* however.

But looking into that further shows:

> ECMAScript implementations must recognize as *WhiteSpace* code points listed in the "Separator, space" (Zs) category by Unicode 5.1.
> 
> ...
>
> NOTE:  Other than for the code points listed in [Table 32](http://www.ecma-international.org/ecma-262/6.0/#table-32), ECMAScript *WhiteSpace* **intentionally excludes** all code points that have the Unicode "White_Space" property but which are not classified in category "Zs".

Which leads to [Unicode PRI 21](http://www.unicode.org/review/resolved-pri.html), where Unicode explicitly moved `U+200B` out of the **Zs** category and into the **Cf** category. 

Thus, going by the ECMAScript 2015 standard (and prior standards too), `String.prototype.trim()` *shouldn't* remove `U+200B` characters from the beginning or end as it doesn't fit the criteria for being a *WhiteSpace* character.

You can confirm this fact by looking at the native implementations of `.trim()` in all browsers. In fact, **string.js** uses the native `.trim()` if it is defined. This is also confirmed by [Mozilla's polyfill for `.trim()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim#Polyfill) *not* removing `\u200B`.

So, if you used the above code snippet, and your environment natively implemented `.trim()` (which NodeJS does), then your code additions would never be executed. The eventual function call would be to the native function, not your custom regular expression replacement.

**Comment by paleite** [comment]
It really baffles me that trim() no longer works the same way. I just wanted to get rid of any excess white space chars on the sides of strings, but trim() no longer does that.

Thanks for taking the time to investigate in such depth!
