### ISSUE TITLE
Support for title case?

### ISSUE THREAD

**Issue by Swathi8** [jprichardson/string.js#188]
Is there any support to convert string to title case?

I didn't find any method in stringjs which converts to title case.

**Comment by firehawkcreative** [comment]
S( "this is a string" ).titleCase().s

You can also use

S( "this_is_a_string" ).humanize().titleCase().s

**Comment by davidlesches** [comment]
S( "this is a string" ).titleCase().s

You can also use

S( "this_is_a_string" ).humanize().titleCase().s

**Comment by Swathi8** [comment]
@davidlesches thanks!
