### ISSUE TITLE
Let trim* method accept arguments

### ISSUE THREAD

**Issue by lijunle** [jprichardson/string.js#91]
I am requesting a new feature. This is about to let trim* method (trim, trimLeft, trimRight) to accept arguments.

The arguments can be:

- A string (char), indicates the string to be trimmed
- A list of strings,indicates the strings to be trimmed
   Or, make the whole argument list as target strings, just like [this proposal][1]

[1]: https://github.com/jprichardson/string.js/issues/75

How do you think about this?

**Comment by zaim** [comment]
:+1:

The `chomp*` methods remove suffixes/prefixes, whereas the above proposed `trim*` methods would remove *all* occurrences of the given characters:

```javascript
S('xyxytest').chompLeft('xy').s //xytest
S('xyxytest').trimLeft('xy').s //test
```

**Comment by az7arul** [comment]
Native trim* methods do not accept any arguments  ( http://www.ecma-international.org/ecma-262/5.1/#sec-15.5.4.20 ). Can this be named something else ?

**Comment by zaim** [comment]
Can't think of a sensible name that haven't been used (`strip` ala Python, `chomp` already used) :)

BTW, `lodash.trim` accepts an argument, but delegates to native `String.prototype.trim` if no arguments given. But I understand how String.js might want to stick as closely to ES specs...

**Comment by jprichardson** [comment]
I'm with @az7arul on this. The difference between `string.js` and `lodash` is that `string.js` also imports native string methods and returns `string.js` objects convenient for chaining, so if developers ever leave `string.js` for native string, they will have the expectation that the methods will behave the same. Think of it more like an implicit contract.

What about adding an optional parameter to the chomp methods indicating the desire to remove all occurances?

**Comment by az7arul** [comment]
@zaim @jprichardson  how about `lstrip` and `rstrip` ? Python's version of these accept `[chars]` arguments ( Ruby has them too but does not accept any argument).

**Comment by jprichardson** [comment]
I like `stripLeft` and `stripRight`... it fits in with the naming schemes of other methods like `trimLeft`, `trimRight`, `padLeft`, `padRight`, etc.

**Comment by az7arul** [comment]
@jprichardson #133
